import type {Metadata} from 'next';
import {Noto_Sans} from 'next/font/google';
import './globals.css';

const notoSans = Noto_Sans({
    variable: '--font-noto-sans',
    subsets: ['latin', 'cyrillic'],
    display: 'swap'
});


export const metadata: Metadata = {
    title: 'Наш проект',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
            <body className={`${notoSans.variable} ${notoSans.className}`}>
                {children}
            </body>
        </html>
    );
}
