export {default as HTag} from './HTag'
export {default as Button} from './Button'
export {default as Paragraph} from './Paragraph'
export {default as Tag} from './Tag'
export {default as Raiting} from './Rating'
export {default as Header} from './Header'
export {default as Footer} from './Footer'
export {default as SideBar} from './SideBar'